apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eptd00trc-go 
  janus-idp.io/tekton: eptd00trc-go
  backstage.io/kubernetes-id: eptd00trc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eptd00trc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml